"use strict";
let places = ["Palestine", "Turkey", "New York", "Japan", "Singapore"];
console.log("Original order:", places);
console.log("Alphabetical order:", [...places].sort());
console.log("Original order:", places);
console.log("Reverse alphabetical order:", [...places].reverse());
console.log("Original order:", places);
places.reverse();
console.log("Reversed order:", places);
places.reverse();
console.log("Original order:", places);
places.sort();
console.log("Aphabetical order:", places);
places.reverse();
console.log("Reverse aphabetical order:", places);
