"use strict";
let a = "Yes";
let b = "No";
let c = 10;
let d = 20;
console.log(" 1: less than from numbers");
console.log(c > d);
console.log(" 2: greater than from strings");
console.log(a > b);
console.log(" 3: greater than from numbers");
console.log(a < b);
console.log(" 4: less than from strings");
console.log(c < d);
console.log(" 5: less than form numbers");
console.log(d > c);
